---
- name: Install gpg
  apt:
    name: gpg
    state: present
  become: yes

- name: Add Virtualbox repository key
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present
  become: yes

- name: Add Virtualbox repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  become: yes

- name: Install Virtualbox
  apt:
    name: "virtualbox-6.1"
  become: yes
