---

- name: Installing packages with APT
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - openssl

- name: Creating certs dir
  include: create_dir.yml
  vars:
    item: "{{ openssl_certs_path }}"
    mode: "0755"

- name: Creating keys dir
  include: create_dir.yml
  vars:
    item: "{{ openssl_keys_path }}"
    mode: "0700"
