---
- name: Install figlet
  apt: name=figlet state=present
  become: yes

- name: Install update motd
  git: repo=https://github.com/adaxi/update-motd.git dest=/etc/update-motd.d clone=yes update=no
  become: yes
  
- name: Remove motd
  file: path=/etc/motd state=absent
  become: yes
  
- name: Symlink
  file: dest=/etc/motd src=/var/run/motd state=link
  become: yes