- name: Create sonarr directories
  file:
    name: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  with_items:
    - /sonarr
    - /sonarr/config

- name: Start sonarr container
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    env:
      "PUID": "1000"
      "PGID": "1000"
    ports:
      - 8989:8989
    restart_policy: "always"
    volumes:
      - /sonarr/config:/config
      - /nas/gamma/series:/tv
      - /deluge/downloads:/downloads