---

- name: Ensure OpenVPN packages are installed
  apt:
    name:
      - openvpn
      - easy-rsa
    state: installed
    update_cache: yes
  become: yes

- name: Ensure that we can start openvpn
  command: systemctl enable openvpn
  become: yes

- name: Copy openvpn defaults file
  copy: src=openvpn_defaults dest=/etc/default/openvpn
  become: yes

- name: Setup openvpn configuration
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf
  become: yes

- name: Copy easy rsa
  command: cp -R /usr/share/easy-rsa /etc/openvpn/easy-rsa
  args:
    creates: /etc/openvpn/easy-rsa

- name: Copy easy-rsa vars
  template: src=ca_vars.j2 dest=/etc/openvpn/easy-rsa/ca_vars
  become: yes

- name: Copy easy-rsa server vars
  template: src=server_vars.j2 dest=/etc/openvpn/easy-rsa/server_vars
  become: yes

- name: Create keys
  file: path=/etc/openvpn/easy-rsa/keys mode=0600 state=directory
  become: yes

- name: Create CA
  shell: ". ./ca_vars && ./pkitool --initca && touch keys/index.txt && echo 01 > keys/serial"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/ca.key

- name: Build DH
  shell: ". ./ca_vars && ./build-dh"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/dh2048.pem

- name: Server Key
  shell: ". ./server_vars && ./pkitool --server {{openvpn_server_key_name}}"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/{{openvpn_server_key_name}}.key


- name: Client keys
  shell: ". ./server_vars && export KEY_OU='{{item}}' && export KEY_NAME='{{item}}' && ./pkitool {{item}}"
  with_items: "{{openvpn_clients}}"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: "/etc/openvpn/easy-rsa/keys/{{item}}.key"

- name: Client configs
  template: src=client.ovpn.j2 dest=/etc/openvpn/easy-rsa/keys/{{item}}.conf
  with_items: "{{openvpn_clients}}"

- name: Create ccd dir
  file: path=/etc/openvpn/ccd state=directory
  become: yes

- name: Restart the server
  service: name=openvpn state=restarted
  become: yes
