---
dependencies:
  - role: common.certificates
    openssl_self_signed: '{{bonaert_eu_openssl_self_signed | default([]) }}'
    letsencrypt: '{{bonaert_eu_letsencrypt | default([]) }}'
  - role: server.nginx