---
- name: Install nginx
  apt: 
    name:
      - nginx-extras
      - python3-passlib
    state: present
  become: yes

- name: Include SSL configuration
  copy: 
    src: ssl.conf 
    dest: /etc/nginx/conf.d/ssl.conf
  become: yes