---
- name: Add numix repository key
  apt_key: keyserver=keyserver.ubuntu.com id=0F164EEB
  become: yes

- name: Add numix repository
  apt_repository: repo='deb http://ppa.launchpad.net/numix/ppa/ubuntu trusty main' state=present
  become: yes

- name: install numix theme and install circle icon theme
  apt: 
    name:
      - numix-icon-theme-circle
      - numix-gtk-theme
      - gnome-tweak-tool
      - nautilus-image-converter
    state: present
  become: yes
  
- name: Create dconf cache dir
  become: yes
  become_user: "{{ansible_user_id}}"
  file:
    path: "~/.cache/dconf"
    state: directory
    owner: "{{ansible_user_id}}"

- name: Install dependencies for gsettings
  apt:
   name: dbus-x11
   state: present
  become: yes

- name: Set icons to numix circle+
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
    key: org.gnome.desktop.interface.icon-theme 
    value: Numix-Circle

- name: Set number of worspaces to 4
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.desktop.wm.preferences.num-workspaces
        value: 4
        
- name: Disable dynamic workspaces
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.shell.overrides.dynamic-workspaces
        value: 'false'
        
- name: Enable workspaces on all screens
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.shell.overrides.workspaces-only-on-primary
        value: 'false'
        
        
- name: Show date
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.desktop.interface.clock-show-date
        value: 'true'
        
- name: Show seconds
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.desktop.interface.clock-show-seconds
        value: 'true'

- name: Add minimize to button layout
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.desktop.wm.preferences.button-layout
        value: ":minimize,close"
        
- name: Set wallpaper
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key:  org.gnome.desktop.background.picture-uri
        value: "file:///usr/share/backgrounds/gnome/Bokeh_Tails.jpg"
        
- name: Remember numlock state
  become: yes
  become_user: "{{ansible_user_id}}"
  gsettings:
        key: org.gnome.settings-daemon.peripherals.keyboard.remember-numlock-state
        value: 'true'


