---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: 
    update_cache: yes
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed.
  apt:
    name:
      - python3-mysqldb
      - mariadb-client
      - mariadb-server
    state: present