---
lusoleaves_com_domain: lusoleaves.com
lusoleaves_com_group: lusoleaves_com
lusoleaves_com_user: lusoleaves_com
lusoleaves_com_home: /var/www/lusoleaves_com
lusoleaves_com_db_host: localhost
lusoleaves_com_db_username: lusoleaves_com
lusoleaves_com_db_name: lusoleaves_com
lusoleaves_com_debug: False

lusoleaves_com_openssl_self_signed:
  - name: '{{lusoleaves_com_domain}}'
    domains: ['www.{{lusoleaves_com_domain}}', '{{lusoleaves_com_domain}}']
    country: 'PT'
    state: 'Algarve'
    city: 'Rogil'
    organization: 'Lusoleaves'
    unit: ''
    email: 'dev@lusoleaves.com'
    days: 3650

lusoleaves_com_letsencrypt:
  - name: '{{lusoleaves_com_domain}}'
    domains: ['{{lusoleaves_com_domain}}', 'www.{{lusoleaves_com_domain}}']
    email: 'dev@adaxisoft.be'