---
- name: Add Microsoft public key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Add Visual Studio Code repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: yes

- name: Download and Install Visual Studio Code
  apt:
    name: code
    state: present
    update_cache: yes
  become: yes
