---
- name: install a media server
  hosts: [mediaservers]
  gather_facts: yes
  become: yes
  become_user: root
  roles:
     - common._base
     - common.devtools
     - media.essencia
     - media.sickbeard
     - media.sabnzbd
     - media.plexmediaserver
     - media.plexhometheater
     - server.omv
