---
- name: install a portainer server
  hosts: [portainerservers]
  gather_facts: yes
  become: yes
  become_user: root
  roles:
      - common._base
      - common.devtools
      - common.tailscale
      - server.docker
      - server.portainer
      - server.deluge
      - server.jackett
      - server.sonarr
      - server.mosquitto
      - server.grott
      - server.eltako-automation
      - role: geerlingguy.ntp # ansible-galaxy install geerlingguy.ntp
        vars:
          ntp_manage_config: true
          ntp_servers:
            - clock.sjc.he.net,
            - clock.fmt.he.net,
            - clock.nyc.he.net
      - server.p1monitor
      - www.home.adaxisoft.be

