---
- name: install a web server
  hosts: [webservers]
  gather_facts: yes
  become: yes
  become_user: root
  roles:
     - common._base
     - common.vim
     - { role: common.dotfiles, install_dofiles: False }
     - common.tailscale
     - server.motd
     - server.docker
     - www.lusoleaves.com
     - www.adaxisoft.be
     - vaultwarden.adaxisoft.be
     - www.bonaert.eu