---

- name: Add Glacier repository key 
  apt_key:
    url: "https://mt-aws.com/vsespb.gpg.key"
    state: present
  become: yes
  
- name: Add Glacier repository
  apt_repository:
    repo: "deb http://dl.mt-aws.com/debian/current {{ ansible_distribution_release }} main"
    state: present
  become: yes
  
- name: Install mtglacier 
  apt:
    name: "libapp-mtaws-perl"
    state: "present"
  become: yes