aptly_user: apt_adaxisoft_be
aptly_home: /var/www/{{aptly_user}}
aptly_secret_key_path: env/{{installation_environment}}/keys/
aptly_secret_key_file: private.gpg.key
aptly_public_key_path: env/{{installation_environment}}/keys/
aptly_public_key_file: public.gpg.key
aptly_virtualhost: apt.adaxisoft.be
aptly_secret_key_id: 7C9E513D
