---
- name: Add Google repository key
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  become: yes

- name: Add Google repository
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
  become: yes

- name: Install Chrome stable
  apt:
    name: google-chrome-stable
  become: yes
