---
dependencies:
  - role: server.nginx
  - role: server.mariadb
  - role: common.certificates
    openssl_self_signed: '{{lusoleaves_com_openssl_self_signed | default([]) }}'
    letsencrypt: '{{lusoleaves_com_letsencrypt | default([]) }}'

