---
dependencies:
  - role: server.nginx
  - role: server.php-fpm
  - role: server.mariadb
  - role: common.certificates
    openssl_self_signed:
      - name: '{{lusoleaves_com_domain}}'
        domains: ['www.{{lusoleaves_com_domain}}', '{{lusoleaves_com_domain}}']
        country: 'PT'
        state: 'Algarve'
        city: 'Rogil'
        organization: 'Lusoleaves'
        unit: ''
        email: 'dev@lusoleaves.com'
        days: 3650
