- name: Install usbipd
  apt:
    name: usbip
    state: present

- name: Copy usbipd unit to server
  copy:
    src: usbip-attach@.service
    dest:  /etc/systemd/system/usbip-attach@.service

- name: Reload systemd
  systemd:
    daemon_reload: true


# Then add binds with:
# 
# systemctl enable usbip-attach@127.0.0.1_1-1.2.3
# systemctl start usbip-attach@127.0.0.1_1-1.2.3