---

- name: create adaxisoft.be group
  group: name="{{adaxisoft_be_group}}" 

- name: create adaxisoft.be user
  user: name="{{adaxisoft_be_user}}" 
        shell=/bin/nologin 
        group="{{adaxisoft_be_group}}" 
        append=yes
        home={{adaxisoft_be_home}}
        createhome=yes
        skeleton=/dev/shm

- name: deploy adaxisoft.be
  git: repo=https://github.com/adaxi/adaxisoft.be.git
       dest="{{adaxisoft_be_home}}"
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: ensure blog directory exists
  file: path="{{adaxisoft_be_home}}/blog" state=directory mode=0755
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: deploy adaxisoft.be/blog
  git: repo=https://github.com/adaxi/adaxisoft-blog.git
       dest="{{adaxisoft_be_home}}/blog"
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: Install nginx configuration
  include: nginx.yml

- name: Install php-fpm configuration
  include: php-fpm.yml

- name: Install nodejs configuration
  include: nodejs.yml

- name: Install php-fpm configuration
  include: mariadb.yml

- name: Restart php-fpm
  service: name=php5-fpm state=restarted

- name: Reload nginx
  service: name=nginx state=reloaded

