---

- name: Create adaxisoft.be group
  group: 
    name: "{{adaxisoft_be_group}}" 

- name: Create adaxisoft.be user
  user: 
    name: "{{adaxisoft_be_user}}" 
    shell: /bin/nologin 
    group: "{{adaxisoft_be_group}}" 
    append: yes
    home: "{{adaxisoft_be_home}}"
    createhome: yes
    skeleton: /dev/shm

- name: Deploy adaxisoft.be
  git: 
    repo: https://github.com/adaxi/adaxisoft.be.git
    dest: "{{adaxisoft_be_home}}"
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: Ensure blog directory exists
  file: 
    path: "{{adaxisoft_be_home}}/blog"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: Deploy adaxisoft.be/blog
  git: 
    repo: https://github.com/adaxi/adaxisoft-blog.git
    dest: "{{adaxisoft_be_home}}/blog"
    version: master
  become: yes
  become_user: "{{adaxisoft_be_user}}"

- name: Install NGINX configuration
  include: nginx.yml

- name: Install nodejs configuration
  include: nodejs.yml

- name: Reload NGINX
  service: name=nginx state=reloaded

