---

- name: Create dav directory
  file: path=/var/dav state=directory owner=www-data group=www-data

- name: Create dav temp directory
  file: path=/var/dav/temp state=directory owner=www-data group=www-data

- name: Create dav temp directory
  file: path=/var/dav/keepass state=directory owner=www-data group=www-data

- name: Generate dav htpasswd file
  htpasswd: path=/etc/nginx/htpasswd name='{{adaxisoft_be_dav_user}}' password='{{adaxisoft_be_dav_passwd}}' owner=root group=root mode=0600

- name: Make adaxisoft_be.conf nginx configuration is available
  template: dest="/etc/nginx/sites-available/adaxisoft_be.conf" src="nginx.adaxisoft_be.conf.j2" 
  notify: reload nginx

- name: Enable nginx adaxisoft_be.conf
  file: src=/etc/nginx/sites-available/adaxisoft_be.conf 
        dest=/etc/nginx/sites-enabled/adaxisoft_be.conf
        state=link
  
