---

- name: Install acl
  apt:
    name: acl
    state: present

- name: Install nginx configuration
  include: nginx.yml

- name: Install mariadb configuration
  include: mariadb.yml

- name: Install lusoleaves.com configuration
  include: container.yml

#- name: Reload nginx
#  service: name=nginx state=reloaded

