---
adaxisoft_be_domain: adaxisoft.be
adaxisoft_be_group: adaxisoft_be
adaxisoft_be_user: adaxisoft_be
adaxisoft_be_home: /var/www/adaxisoft_be

adaxisoft_be_openssl_self_signed:
  - name: '{{adaxisoft_be_domain}}'
    domains: ['{{adaxisoft_be_domain}}', 'www.{{adaxisoft_be_domain}}']
    country: 'BE'
    state: 'Brussels'
    city: 'Brussels'
    organization: 'adaxisoft.be'
    unit: ''
    email: 'dev@adaxisoft.be'
    days: 3650

adaxisoft_be_letsencrypt:
  - name: '{{adaxisoft_be_domain}}'
    domains: ['{{adaxisoft_be_domain}}', 'www.{{adaxisoft_be_domain}}']
    email: 'dev@adaxisoft.be'
