- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install bridge-utils
  apt:
    name:
      - bridge-utils
      - net-tools

- name: Remove 'source-directory' from /etc/network/interfaces as it breaks installation of ifupdown2 requirement of proxmox
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    state: absent
    regexp: '^source-directory'

- name: Create /volumes/proxmox directory 
  ansible.builtin.file:
    path: /volumes/proxmox
    state: directory
    mode: '0755'

- name: Install proxmox depdendencies
  apt:
    name:
      - python3-proxmoxer
      - python3-requests

- name: Create group
  group:
    name: adaxi
    state: present

- name: Create an account for adaxi
  ansible.builtin.user:
    state: present
    name: adaxi
    password: '$y$j9T$Qqtdii04kowsWFOENHguQ.$6GBgzmrfljpwaAU3s7M6vAgd0YTTdy.BhVN4gGemuD5' # adaxi
    update_password: 'on_create'
    shell: /bin/bash
    group: adaxi
    append: yes
    groups:
      - sudo




