---
# Variable setup.
- name: Define php_conf_path
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

- name: Define php_extension_conf_path
  set_fact:
    php_extension_conf_path: "{{ __php_extension_conf_path }}"
  when: php_extension_conf_path is not defined

- name: Define php_opcache_conf_filename
  set_fact:
    php_opcache_conf_filename: "{{ __php_opcache_conf_filename }}"
  when: php_opcache_conf_filename is not defined

# Setup/install tasks.
- include: install.yml

# Configure PHP.
- include: configure.yml
