---
- name: Install development tools
  apt:
    name: stow
    state: present
  become: yes

- name: Clone all dot files
  git:
    repo: "https://github.com/adaxi/.dotfiles"
    dest: "/home/{{ ansible_user_id }}/.dotfiles"
    version: master
    update: yes
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install all dotfiles
  shell: "/usr/bin/find * -mindepth 0 -maxdepth 0 -type d -not -path '*/\\.*' -exec stow {} \\;"
  args:
    chdir: "/home/{{ ansible_user_id }}/.dotfiles"
  when: install_dotfiles
  become: yes
  become_user: "{{ ansible_user_id }}"
  changed_when: False