- name: Make home_adaxisoft_be.conf nginx configuration is available
  template:
    dest: /etc/nginx/sites-available/home_adaxisoft_be.conf
    src: nginx.home_adaxisoft_be.conf.j2
  notify: reload nginx
  when: installation_environment == "production"

- name: Enable nginx home_adaxisoft_be.conf
  file:
    src: /etc/nginx/sites-available/home_adaxisoft_be.conf
    dest: /etc/nginx/sites-enabled/home_adaxisoft_be.conf
    state: link
  when: installation_environment == "production"