---
aptly_repositories:
  - name: debian-wheezy
    comment: adaxisoft apt repository for wheezy packages
    prefix: debian
    distribution: wheezy
    component: main
    
  - name: debian-jessie
    comment: adaxisoft apt repository for jessie packages
    prefix: debian
    distribution: jessie
    component: main

  - name: debian-stretch
    comment: adaxisoft apt repository for stretch packages
    prefix: debian
    distribution: stretch
    component: main
   