
- name: Add Tailscape repository key 
  apt_key:
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
    state: present
  become: yes
  
- name: Add Tailscale repository
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main"
    state: present
  become: yes
  
- name: Install tailscale 
  apt:
    name: tailscale
    state: "present"
  become: yes