---

- name: Ensure SickBeard service group exists
  group:
    name: "{{ sickbeard_group_name }}"
    state: present
          
- name: Ensure SickBeard service user exists
  user: 
    name: "{{ sickbeard_user_name }}"
    group: "{{ sickbeard_group_name }}"
    shell: "/usr/sbin/nologin"
    home: "{{ sickbeard_user_home }}"
    createhome: yes
    state: present

- name: Ensure SickBeard service user environment is set up
  shell: "cp /etc/skel/{.bash*,.login,.profile} {{ sickbeard_user_home }}/"
  args:
    creates: "{{ sickbeard_user_home }}/.bashrc"
    
- name: Ensure SickBeard dependencies are installed
  apt:
    name: sickbeard
    state: present

# When stopping sickbeard writes is configuration to the disk
# and overwrites potential configuration written by ansible
- name: Ensure SickBeard service is stopped to write configuration
  service: 
    name: sickbeard
    state: stopped
    enabled: yes
  
- name: Copy defaults values
  template: 
    src: sickbeard.defaults.j2 
    dest: /etc/default/sickbeard
    owner: "{{ sickbeard_user_name }}"
  notify: Restart Sickbeard
      
- name: Ensure SickBeard config directory exists
  file:
    dest: "{{ sickbeard_conf_path }}"
    owner: "{{ sickbeard_user_name }}"
    group: "{{ sickbeard_group_name }}"
    state: directory
  
- name: Create default configuration for sickbeard in sickbeard.ini
  template: 
    src: sickbeard.config.ini.j2 
    dest: "{{ sickbeard_conf_path }}/sickbeard.ini"
    owner: "{{ sickbeard_user_name }}"
    group: "{{ sickbeard_group_name }}"
    mode: "0644"
  notify: Restart Sickbeard

- name: Ensure SickBeard logs directory exists
  file: 
    dest: "{{ sickbeard_logs_dir }}"
    owner: "{{ sickbeard_user_name }}"
    recurse: yes 
    state: directory

- name: Ensure SickBeard service is running and enabled on boot
  service:
    name: sickbeard 
    pattern: sickbeard
    state: started 
    enabled: yes
